# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{refinerycms-forem}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Uckun", "Ryan Bigg"]
  s.date = %q{2011-03-16}
  s.description = %q{A port of forem to  refinerycms}
  s.email = %q{tim@uckun.com}
  s.files = [
    "app/models/forem/forum.rb",
    "app/models/forem/post.rb",
    "app/models/forem/topic.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/refinerycms-forum.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby on Rails forum engine for RefineryCMS}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<refinerycms>, [">= 0.9.9"])
    else
      s.add_dependency(%q<refinerycms>, [">= 0.9.9"])
    end
  else
    s.add_dependency(%q<refinerycms>, [">= 0.9.9"])
  end
end

